# Generated by Django 3.2.16 on 2022-12-26 11:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_tag_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('name',), 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='ingredientamount',
            options={'ordering': ('recipe',), 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Количество ингредиентов'},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(1, 'Введите обозначение единицы измерения')], verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3, 'введите более 3 символов')], verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, 'Минимальное значение 1'), django.core.validators.MaxValueValidator(10000, 'Максимальное значение 10000'), django.core.validators.RegexValidator('^[0-9]+$', 'Количество ингредиента может быть только числом от 1 до 10000')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='ingredientamount',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_amount', to='recipes.ingredient', verbose_name='Связанные ингредиенты'),
        ),
        migrations.AlterField(
            model_name='ingredientamount',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_amount', to='recipes.recipe', verbose_name='В рецептах'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, 'Минимальное значение 1 минута'), django.core.validators.MaxValueValidator(300, 'Максимальное значение 300 минут'), django.core.validators.RegexValidator('^[0-9]+$', 'Время приготовления может быть только числом от 1 до 300')], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3, 'введите более 3 символов'), django.core.validators.RegexValidator('^[a-zA-Zа-яА-Я ]+$', 'Название рецепта может состоять только из русских, латниских букв и пробела между словами')], verbose_name='Название блюда'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, default='#', max_length=7, null=True, unique=True, validators=[django.core.validators.RegexValidator('^#([A-Fa-f0-9]{6})$', 'введите код цвета в формате #F08080')], verbose_name='Цветовой HEX-код'),
        ),
    ]
