# Generated by Django 3.2.16 on 2022-12-26 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3, 'введите более 3 символов')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3, 'введите более 3 символов')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'введите более 3 символов'), django.core.validators.RegexValidator('^[a-zA-Zа-яА-Я0-9@.]+$', '"Имя пользователя" может содержать русские латинские символы, цифры 0-9, знак ".", знак "@"')], verbose_name='Уникальное имя пользователя'),
        ),
    ]
